packages:
  - "packages/*"
minimumReleaseAgeExclude:
  - '@anthropic-ai/claude-agent-sdk'
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  msw: true
  node-datachannel: true
  sharp: true
  workerd: true
nodeLinker: hoisted
